[WIP] adding cluster formation script
aws-quickstart/quickstart-aerospike pull request #12
Opened 2021-06-10 23:58 UTC by sourabh3b

@gargana I am getting following error and working on fixing it, can you please take a look and let me know if you've seen something similar ? I'm trying to follow something similar [here](https://github.com/aws-quickstart/quickstart-hashicorp-vault/blob/main/templates/quickstart-hashicorp-vault.template#L1064-L1067)

```bash
$ taskcat test run
 _            _             _   
| |_ __ _ ___| | _____ __ _| |_ 
| __/ _` / __| |/ / __/ _` | __|
| || (_| \__ \   < (_| (_| | |_ 
 \__\__,_|___/_|\_\___\__,_|\__|
                                

version 0.9.23
[INFO   ] : Linting passed for file: /Users/sourabh/go/src/github.com/sourabh3b/quickstart-aerospike/templates/aerospike-cluster-entrypoint-new-vpc.template.yaml
[ERROR  ] : ---
[ERROR  ] : Linting detected issues in: /Users/sourabh/go/src/github.com/sourabh3b/quickstart-aerospike/templates/aerospike-cluster-workload.template.yaml
[ERROR  ] :     line 362 [1019] [Sub validation of parameters] Sub should be an array of 2 for Resources/LaunchConfig/Metadata/AWS::CloudFo
                                                     rmation::Init/config/files//opt/aerospike/cft_scripts/aerospike_cluster/cont
                                                     ent/Fn::Sub
[ERROR  ] :     line 369 [1012] [Check if Refs exist] Ref QSS3BucketName not found as a resource or parameter
[ERROR  ] :     line 369 [1019] [Sub validation of parameters] Parameter QSS3BucketName for Fn::Sub not found at Resources/LaunchConfig/Met
                                                     adata/AWS::CloudFormation::Init/config/files//opt/aerospike/cft_scripts/aero
                                                     spike_cluster/content/Fn::Sub/2/S3Bucket/Fn::If/1/Fn::Sub
[ERROR  ] :     line 369 [8002] [Check if the referenced Conditions are defined] Condition UsingDefaultBucket is not defined.
[WARN   ] : No stacks were created... skipping cleanup.
[ERROR  ] : Lint failed with errors
```

2021-06-11 16:10 UTC, gargana requested changes
See my comments.

2021-06-11 16:10 UTC, gargana commented on templates/aerospike-cluster-workload.template.yaml
> +                - S3Bucket: !If [UsingDefaultBucket, !Sub '${QSS3BucketName}-${AWS::Region}', !Ref QSS3BucketName]
The "-" in front of S3Bucket  here is causing an issue. 
It should rather be:
```
 - REGION: !Sub "${AWS::Region}" 
   S3Bucket: !If [UsingDefaultBucket, !Sub '${QSS3BucketName}-${AWS::Region}', !Ref QSS3BucketName]
```
The QSS3BucketName is not being sent to this stack which is why it is complaining:
```
[Sub validation of parameters] Parameter QSS3BucketName for Fn::Sub not found
```

This should be as simple as passing the "QSS3BucketName" to the template.

2021-06-15 05:13 UTC, gargana requested changes
Hi Sourabh

Please see the requested changes.

Will merge as soon as they are in.

Thanks,

Andrew

2021-06-15 05:13 UTC, gargana commented on templates/aerospike-cluster-workload.template.yaml
> +                  - arn:${AWS::Partition}:s3:::${S3Bucket}/${QSS3KeyPrefix}*
Can we make this explicitly the file path
```
- arn:${AWS::Partition}:s3:::${S3Bucket}/${QSS3KeyPrefix}scripts/aerospike_cluster.sh
```

2021-06-15 05:13 UTC, gargana commented on templates/aerospike-cluster-workload.template.yaml
>                  Action: 'autoscaling:*'
Can we provide the specific autoscaling actions required here?

2021-06-15 09:04 UTC, sourabh3b commented
updated PR comments, please take a look

2021-06-16 12:26 UTC, gargana approved these changes
LGTM - Shipping

2021-06-16 12:26 UTC, merged